name: Azure Cleanup
# Destroy Azure Resources

on:
  workflow_dispatch:

env:
  AZURE_BLOB_STORAGE: ${{ vars.AZURE_BLOB_STORAGE }}
  AZURE_BLOB_STORAGE_TF_STATE_CONTAINER: ${{ vars.AZURE_BLOB_STORAGE_TF_STATE_CONTAINER }}

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse tool versions
        uses: endorama/asdf-parse-tool-versions@v1

      - name: Run Terraform Destroy
        uses: ./.github/actions/terraform-destroy
